### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by JulioC3094** [Balthair94/MHAssignment01#7]
Hello Baltazar
-You should comment your code and explain what it do.
-If you represent a percentage whit the bars, you must write on number down of them.
-In the part of your projects with two points is more than enough not to have to click each one.
-In hobbies, the hyperlinks to pages are not necessary. Everyone here knows about the games, anime, cartoons. Otherwise exist Google.

**Comment by Balthair94** [comment]
Hello Julio
- Comments added.
- I don't show the porcentage because to see it you have to press the image. Now I changed that, so you have to pass the mouse over the image to see the porcentage.
- I changed that part and now you only can see one of my projects when you made click on one of them.
- I think that they are necesary because one objective in UX is that you don't have to let the user think to much. Besides, I think that is incorrect to think that everybody knows about Overwatch (that my hobby, not all video games) and anime, may be cartoons, but well...

Thanks for your comments.
